// Cores reais das camisas/escudos de cada time (aproximadas) -- usadas
// como identidade visual provisoria ate termos os escudos de verdade.
export const CORES_TIME: Record<string, { fundo: string; borda: string; textoEscuro?: boolean }> = {
  "Athletico-PR": { fundo: "#C8102E", borda: "#000000" },
  "Atlético-MG": { fundo: "#000000", borda: "#FFFFFF" },
  Bahia: { fundo: "#0038A8", borda: "#E4022C" },
  Botafogo: { fundo: "#000000", borda: "#FFFFFF" },
  Chapecoense: { fundo: "#1B7B3A", borda: "#FFFFFF" },
  Corinthians: { fundo: "#000000", borda: "#FFFFFF" },
  Coritiba: { fundo: "#0F7A3D", borda: "#FFFFFF" },
  Cruzeiro: { fundo: "#003DA5", borda: "#FFFFFF" },
  Flamengo: { fundo: "#C8102E", borda: "#000000" },
  Fluminense: { fundo: "#8B1538", borda: "#046A38" },
  Grêmio: { fundo: "#0D80C7", borda: "#000000" },
  Internacional: { fundo: "#E2001A", borda: "#FFFFFF" },
  Mirassol: { fundo: "#FFD400", borda: "#1B7B3A", textoEscuro: true },
  Palmeiras: { fundo: "#006437", borda: "#FFFFFF" },
  "Red Bull Bragantino": { fundo: "#D50032", borda: "#FFFFFF" },
  Remo: { fundo: "#0033A0", borda: "#FFFFFF" },
  Santos: { fundo: "#FFFFFF", borda: "#000000", textoEscuro: true },
  "São Paulo": { fundo: "#C1121C", borda: "#000000" },
  "Vasco da Gama": { fundo: "#000000", borda: "#FFFFFF" },
  Vitória: { fundo: "#C8102E", borda: "#000000" },

  // Premier League
  Arsenal: { fundo: "#EF0107", borda: "#063672" },
  "Aston Villa": { fundo: "#670E36", borda: "#95BFE5" },
  Bournemouth: { fundo: "#DA291C", borda: "#000000" },
  Brentford: { fundo: "#E30613", borda: "#000000" },
  Brighton: { fundo: "#0057B8", borda: "#FFFFFF" },
  Chelsea: { fundo: "#034694", borda: "#FFFFFF" },
  Coventry: { fundo: "#6CADDF", borda: "#000000" },
  "Crystal Palace": { fundo: "#C4122E", borda: "#1B458F" },
  Everton: { fundo: "#003399", borda: "#FFFFFF" },
  Fulham: { fundo: "#FFFFFF", borda: "#000000", textoEscuro: true },
  "Hull City": { fundo: "#000000", borda: "#F5A623" },
  Ipswich: { fundo: "#0044A9", borda: "#FFFFFF" },
  Leeds: { fundo: "#FFFFFF", borda: "#1D428A", textoEscuro: true },
  Liverpool: { fundo: "#C8102E", borda: "#F6EB61" },
  "Manchester City": { fundo: "#6CABDD", borda: "#1C2C5B" },
  "Manchester United": { fundo: "#DA291C", borda: "#000000" },
  "Newcastle United": { fundo: "#000000", borda: "#FFFFFF" },
  "Nottingham Forest": { fundo: "#DA020E", borda: "#FFFFFF" },
  Sunderland: { fundo: "#EB172B", borda: "#000000" },
  Tottenham: { fundo: "#FFFFFF", borda: "#132257", textoEscuro: true },

  // La Liga
  Alavés: { fundo: "#002F87", borda: "#FFFFFF" },
  "Athletic Club": { fundo: "#EE2523", borda: "#000000" },
  "Atlético Madrid": { fundo: "#CB3524", borda: "#272E61" },
  Barcelona: { fundo: "#004D98", borda: "#A50044" },
  "Celta de Vigo": { fundo: "#0F6EB4", borda: "#FFFFFF" },
  "Deportivo La Coruña": { fundo: "#0057A8", borda: "#FFFFFF" },
  Elche: { fundo: "#0B7B3E", borda: "#FFFFFF" },
  Espanyol: { fundo: "#0A5FA8", borda: "#FFFFFF" },
  Getafe: { fundo: "#003399", borda: "#FFFFFF" },
  Levante: { fundo: "#002157", borda: "#E2001A" },
  Malaga: { fundo: "#1160AA", borda: "#FFFFFF" },
  Osasuna: { fundo: "#D2122E", borda: "#0A2240" },
  "Racing Santander": { fundo: "#009640", borda: "#FFFFFF" },
  "Rayo Vallecano": { fundo: "#FFFFFF", borda: "#D2001C", textoEscuro: true },
  "Real Betis": { fundo: "#00954C", borda: "#FFFFFF" },
  "Real Madrid": { fundo: "#FFFFFF", borda: "#FEBE10", textoEscuro: true },
  "Real Sociedad": { fundo: "#0B69AD", borda: "#FFFFFF" },
  "Sevilla FC": { fundo: "#D2001C", borda: "#FFFFFF" },
  Valencia: { fundo: "#FFFFFF", borda: "#EE7203", textoEscuro: true },
  Villarreal: { fundo: "#FFE667", borda: "#00529F", textoEscuro: true },

  // Bundesliga
  "1899 Hoffenheim": { fundo: "#1961B5", borda: "#FFFFFF" },
  "Bayer Leverkusen": { fundo: "#E32221", borda: "#000000" },
  "Bayern Munich": { fundo: "#DC052D", borda: "#0066B2" },
  "Borussia Dortmund": { fundo: "#FDE100", borda: "#000000", textoEscuro: true },
  "Borussia Mönchengladbach": { fundo: "#FFFFFF", borda: "#000000", textoEscuro: true },
  "Eintracht Frankfurt": { fundo: "#E1000F", borda: "#000000" },
  "FC Augsburg": { fundo: "#BA3733", borda: "#007A3D" },
  "FC Koln": { fundo: "#ED1C24", borda: "#FFFFFF" },
  "FC Schalke 04": { fundo: "#004D9D", borda: "#FFFFFF" },
  "FSV Mainz 05": { fundo: "#C3141E", borda: "#FFFFFF" },
  "Hamburger SV": { fundo: "#12294B", borda: "#FFFFFF" },
  "RB Leipzig": { fundo: "#DA141B", borda: "#FFFFFF" },
  "SC Freiburg": { fundo: "#E2001A", borda: "#000000" },
  "SC Paderborn 07": { fundo: "#0057A0", borda: "#FFFFFF" },
  "SV Elversberg": { fundo: "#0A3B78", borda: "#000000" },
  "Union Berlin": { fundo: "#EB1923", borda: "#FFFFFF" },
  "VfB Stuttgart": { fundo: "#FFFFFF", borda: "#E32219", textoEscuro: true },
  "Werder Bremen": { fundo: "#00963F", borda: "#FFFFFF" },

  // Serie A
  "AC Milan": { fundo: "#FB090B", borda: "#000000" },
  "AS Roma": { fundo: "#8E1F2F", borda: "#F0BC42" },
  Atalanta: { fundo: "#274FA3", borda: "#000000" },
  Bologna: { fundo: "#A6170F", borda: "#142B54" },
  Cagliari: { fundo: "#C8102E", borda: "#002B5C" },
  Como: { fundo: "#003399", borda: "#FFFFFF" },
  Fiorentina: { fundo: "#522398", borda: "#FFFFFF" },
  Frosinone: { fundo: "#FFD400", borda: "#003DA5", textoEscuro: true },
  Genoa: { fundo: "#B4292F", borda: "#10275C" },
  Inter: { fundo: "#010E80", borda: "#000000" },
  Juventus: { fundo: "#000000", borda: "#FFFFFF" },
  Lazio: { fundo: "#A9D6E5", borda: "#000000", textoEscuro: true },
  Lecce: { fundo: "#FCE300", borda: "#C8102E", textoEscuro: true },
  Monza: { fundo: "#D6001C", borda: "#FFFFFF" },
  Napoli: { fundo: "#12A0D7", borda: "#FFFFFF" },
  Parma: { fundo: "#F7CA05", borda: "#002B5C", textoEscuro: true },
  Sassuolo: { fundo: "#0D6A42", borda: "#000000" },
  Torino: { fundo: "#7B0C1E", borda: "#FFFFFF" },
  Udinese: { fundo: "#000000", borda: "#FFFFFF" },
  Venezia: { fundo: "#F5821F", borda: "#000000" },

  // Ligue 1
  Angers: { fundo: "#000000", borda: "#FFFFFF" },
  Auxerre: { fundo: "#FFFFFF", borda: "#002E62", textoEscuro: true },
  "Estac Troyes": { fundo: "#003C82", borda: "#FFFFFF" },
  "LE Havre AC": { fundo: "#041E42", borda: "#7BAFD4" },
  "Le Mans": { fundo: "#002F6C", borda: "#FFFFFF" },
  Lens: { fundo: "#E5231B", borda: "#FFD700" },
  Lille: { fundo: "#E01E13", borda: "#003DA5" },
  Lorient: { fundo: "#FF6600", borda: "#000000" },
  Lyon: { fundo: "#0E1E5B", borda: "#FFFFFF" },
  Marseille: { fundo: "#FFFFFF", borda: "#2FAEE0", textoEscuro: true },
  Monaco: { fundo: "#E2231A", borda: "#FFFFFF" },
  Nice: { fundo: "#ED1C24", borda: "#000000" },
  "Paris FC": { fundo: "#1B2A5B", borda: "#ED1C24" },
  "Paris Saint Germain": { fundo: "#004170", borda: "#DA291C" },
  "Rennes FC": { fundo: "#E2001A", borda: "#000000" },
  "Stade Brestois 29": { fundo: "#E2001A", borda: "#FFFFFF" },
  Strasbourg: { fundo: "#0A4B9E", borda: "#FFFFFF" },
  Toulouse: { fundo: "#6A1B70", borda: "#FFFFFF" },
};

export function corTime(nome: string) {
  return CORES_TIME[nome] ?? { fundo: "#3f3f46", borda: "#71717a" };
}

export function iniciais(nome: string) {
  const partes = nome.replace(/-/g, " ").split(" ").filter(Boolean);
  if (partes.length === 1) return partes[0].slice(0, 2).toUpperCase();
  return (partes[0][0] + partes[partes.length - 1][0]).toUpperCase();
}

// Abreviacao de 3 letras pro nome do adversario nas colunas da grade de
// estatistica -- coluna larga o suficiente pro nome inteiro deixava o
// numero da celula pequeno e desproporcional (ver conversa 2026-09-03).
const ABREVIACAO_TIME: Record<string, string> = {
  "Athletico-PR": "CAP",
  "Atlético-MG": "CAM",
  Bahia: "BAH",
  Botafogo: "BOT",
  Chapecoense: "CHA",
  Corinthians: "COR",
  Coritiba: "CTB",
  Cruzeiro: "CRU",
  Flamengo: "FLA",
  Fluminense: "FLU",
  Grêmio: "GRE",
  Internacional: "INT",
  Mirassol: "MIR",
  Palmeiras: "PAL",
  "Red Bull Bragantino": "RBB",
  Remo: "REM",
  Santos: "SAN",
  "São Paulo": "SPO",
  "Vasco da Gama": "VAS",
  Vitória: "VIT",

  // Premier League
  Arsenal: "ARS",
  "Aston Villa": "AVL",
  Bournemouth: "BOU",
  Brentford: "BRE",
  Brighton: "BHA",
  Chelsea: "CHE",
  Coventry: "COV",
  "Crystal Palace": "CRY",
  Everton: "EVE",
  Fulham: "FUL",
  "Hull City": "HUL",
  Ipswich: "IPS",
  Leeds: "LEE",
  Liverpool: "LIV",
  "Manchester City": "MCI",
  "Manchester United": "MUN",
  "Newcastle United": "NEW",
  "Nottingham Forest": "NFO",
  Sunderland: "SUN",
  Tottenham: "TOT",

  // La Liga
  Alavés: "ALA",
  "Athletic Club": "ATH",
  "Atlético Madrid": "ATM",
  Barcelona: "BAR",
  "Celta de Vigo": "CEL",
  "Deportivo La Coruña": "DEP",
  Elche: "ELC",
  Espanyol: "ESP",
  Getafe: "GET",
  Levante: "LEV",
  Malaga: "MAL",
  Osasuna: "OSA",
  "Racing Santander": "RAC",
  "Rayo Vallecano": "RAY",
  "Real Betis": "BET",
  "Real Madrid": "RMA",
  "Real Sociedad": "RSO",
  "Sevilla FC": "SEV",
  Valencia: "VAL",
  Villarreal: "VIL",

  // Bundesliga
  "1899 Hoffenheim": "HOF",
  "Bayer Leverkusen": "LEV",
  "Bayern Munich": "FCB",
  "Borussia Dortmund": "BVB",
  "Borussia Mönchengladbach": "BMG",
  "Eintracht Frankfurt": "SGE",
  "FC Augsburg": "FCA",
  "FC Koln": "KOE",
  "FC Schalke 04": "S04",
  "FSV Mainz 05": "M05",
  "Hamburger SV": "HSV",
  "RB Leipzig": "RBL",
  "SC Freiburg": "SCF",
  "SC Paderborn 07": "SCP",
  "SV Elversberg": "ELV",
  "Union Berlin": "FCU",
  "VfB Stuttgart": "VFB",
  "Werder Bremen": "SVW",

  // Serie A
  "AC Milan": "MIL",
  "AS Roma": "ROM",
  Atalanta: "ATA",
  Bologna: "BOL",
  Cagliari: "CAG",
  Como: "COM",
  Fiorentina: "FIO",
  Frosinone: "FRO",
  Genoa: "GEN",
  Inter: "INT",
  Juventus: "JUV",
  Lazio: "LAZ",
  Lecce: "LEC",
  Monza: "MON",
  Napoli: "NAP",
  Parma: "PAR",
  Sassuolo: "SAS",
  Torino: "TOR",
  Udinese: "UDI",
  Venezia: "VEN",

  // Ligue 1
  Angers: "ANG",
  Auxerre: "AUX",
  "Estac Troyes": "TRO",
  "LE Havre AC": "HAC",
  "Le Mans": "LEM",
  Lens: "LEN",
  Lille: "LIL",
  Lorient: "LOR",
  Lyon: "LYO",
  Marseille: "OM",
  Monaco: "ASM",
  Nice: "NIC",
  "Paris FC": "PFC",
  "Paris Saint Germain": "PSG",
  "Rennes FC": "REN",
  "Stade Brestois 29": "BRS",
  Strasbourg: "STR",
  Toulouse: "TFC",
};

export function abreviarTime(nome: string) {
  return ABREVIACAO_TIME[nome] ?? nome.replace(/[^a-zA-ZÀ-ÿ]/g, "").slice(0, 3).toUpperCase();
}
